[global]

# Desactiva algunos warnings para una mejor experiencia
developmentMode = false

[server]
# Configuración del servidor
headless = true
port = 8501
enableCORS = true
enableXsrfProtection = false

[browser]
# Configuración del navegador
gatherUsageStats = false
