[global]

# Desactiva algunos warnings para una mejor experiencia
developmentMode = false

[server]
# Configuración del servidor
headless = true
port = 8501
enableCORS = true
enableXsrfProtection = false

[browser]
# Configuración del navegador
gatherUsageStats = false
[theme]
base = "dark"
primaryColor = "#792EE5"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1A1C24"
textColor = "#FAFAFA"
font = "sans serif"
